# Generated by Django 2.2.6 on 2021-06-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourvariant',
            name='date',
        ),
        migrations.AddField(
            model_name='tourvariant',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Тур активен'),
        ),
    ]
